### PR TITLE
Chef 17 compatiblity changes

### PR DESCRIPTION
**Pull request by bmhughes**
- Enable resource unified_mode for Chef 17 compatibility
- Chefspec platform update
- Update kitchen platforms

Also, as a side note, if you weren't looking to maintain this cookbook going forward would you be interested in donating it to the [sous-chefs](https://sous-chefs.org/)?

### CODE REVIEW

**Comment by joyofhex** [comment]
This looks good to me, but would you consider addressing the test failures in CI?

Thanks for your contribution! I'll also take a look at sous-chefs.

**Comment by bmhughes** [comment]
> 
> 
> This looks good to me, but would you consider addressing the test failures in CI?
> 
> Thanks for your contribution! I'll also take a look at sous-chefs.

Should be passing now

**Comment by joyofhex** [comment]
Thanks for the contribution!

**Comment by ramereth** [comment]
@joyofhex can you please release a new version of this cookbook on the supermarket?

**Pull request merged**
