### PR TITLE
Add reload support

### PR DESCRIPTION
**Pull request by mengesb**
* Change restart/reload behavior
* Reload on zone change
* Restart on named service configuration change
* Using include directive to include forward, master, secondary zone definitions
* Addresses #35 

Signed-off-by: [Brian Menges](https://github.com/mengesb)

### CODE REVIEW

**Comment by mengesb** [comment]
@joyofhex So the PR is rather large because in order to really support the correct reload behavior I needed to break off the zones from the main configuration file. This should also allow some tighter control later on supporting zone view reloading via rndc. (applies only to masters).

**Comment by mengesb** [comment]
Going to ping you here again as well @joyofhex , since I did see you responded on the other PR. I'm pretty sure this will have a merge conflict once the other PR is merged in however wanted to bring your attention here too.

**Comment by joyofhex** [comment]
I'm not sure I understand why you need to break the zones out into separate files. I did a bit of experimenting a few weeks back with straight swapping all the :restarts for :reloads and that seemed to be sufficient for most cases. I believe I could have just used reload everywhere I used restart and everything would work. 

I'm not a big fan of adding type codes to objects; perhaps it's time to promote the structs into fully realised objects that can render themselves?

**Comment by mengesb** [comment]
So one reason, which is common practice, is to group zones based on type (forward, master, slave).

The main reason is that there are configuration circumstances when you'd want to perform an `rndc reconfigure` vs `rndc reload` . Reconfigure is for adding/removing zones and updating bind server configuration. Reload is for re-reading existing configuration.

Generally speaking I separated the two because more often than not most want to restart the service when there's a server level change (options, etc) vs reload (most often related to zone files).

Since you didn't structure anything operative for RNDC calls specifically we're left with the constructs of the service. Reloads message only `rndc reload` and restarts perform a stop/start for most platforms supported. I basically drew a line in the sand - if you're modifying the server's base operation (not runtime operation), then you'd likely intend to restart vs reload (runtime change)

**Comment by mengesb** [comment]
Not entirely sure that I know what you mean by fully realized objects however I wanted an easier way to use 1 template for all zone types, and that was the method that was quickest to implement in my head. If this isn't the direction you'd like to go I'm all ears

**Pull request closed without merging**
