### PR TITLE
Support bind/named in chroot configuration

### PR DESCRIPTION
**Pull request by mengesb**
* Add support for chrooted install
* Chroot Supported platforms: CentOS/RedHat 6.x+, Debian 8.x+, Ubuntu 14.04 LTS
* Chroot Incompatible platforms: Ubuntu 16.04 LTS [ubuntu/+source/bind9/+bug/1630025](https://bugs.launchpad.net/ubuntu/+source/bind9/+bug/1630025)
* Updated rndc call to be compliant with current auto-configuration standards
* Updated file paths using `::File,join()` method
* Delayed all template creation to avoid file busy conflicts
* Added `.kitchen.dokken.yml` for faster testing with [kitchen-dokken](https://github.com/someara/kitchen-dokken)
* Added support for env var `CHEF_VERSION` to affect kitchen-dokken chef-client version
* Supports chef-client version 12.21.26 and 13.6.4

Signed-off-by: Brian Menges <mengesb@gmail.com>

### CODE REVIEW

**Comment by mengesb** [comment]
This should resolve #31

**Comment by joyofhex** [comment]
Thanks for your contribution. I'll check this out a little later today and then merge as it looks good to me.

**Comment by mengesb** [comment]
If you've got a current chefdk, you should have kitchen-dokken. To run the inspec tests faster you can:
* 12.21.26 - `KITCHEN_YAML=.kitchen.dokken.yml kitchen test`
* 13.6.4 - `CHEF_VERSION=13.6.4 KITCHEN_YAML=.kitchen.dokken.yml kitchen test`

This should run the full suite in ~13 minutes.

**Comment by joyofhex** [comment]
Thanks for the tips on dokken, very interesting tool that I've never used before.

However, the tests seem to fail on CentOS 6 and 7 for me. It looks like this is because the bind-chroot package will union mount the files from /etc into the chroot folder if they don't already exist. See the error here:

https://gist.github.com/joyofhex/03178421aaa2a26532bca3f17524ea44

It's been a while since I ran with bind-chroot installed on centos, but I think the idea there is that you keep all the config files in the standard locations and let the union magic happen (though I was never convinced that was a great idea).

**Comment by mengesb** [comment]
So... I can do one of two things... I can remove the paths in the instance of `chroot`... or I can remove the chroot handles on the helper method since it would be deemed unnecessary per your comment about the union file system right?

**Comment by mengesb** [comment]
Looks like deleting the target union directory is a no-go. So I'm tinkering with updates to the helper for redhat. Per Debian, there's still a need to create all the stuffs in `/var/bind9/chroot/...` ultimately... and it all operates in that world and there's no union file system magic

**Comment by mengesb** [comment]
OK - this should solve the GIST you posted now. I've removed the redirection of file generation on RHEL family oses, updated the unit tests, and also covered the remaining missed units.

100% RSpec/InSpec/Cookstyle/Foodcritic passing

**Comment by mengesb** [comment]
with the union magic, would I need to be creating the zone files (db....) in the chroot path ?

**Comment by joyofhex** [comment]
Great. That seems to work. I've tried it out on a couple of my own nameservers and they're now running inside a chroot.

**Pull request merged**
